name: ml_advisor_app 
description: ML Advisor - Model Selection for Bug Prediction 
publish_to: 'none' 
version: 1.0.0+1 
 
environment: 
  sdk: '>=3.0.0 <4.0.0' 
 
dependencies: 
  flutter: 
    sdk: flutter 
   
  # Firebase 
  firebase_core: ^3.13.0 
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.1
   
  # State Management 
  provider: ^6.1.5+1 
   
  # HTTP 
  http: ^1.2.0 
   
  # Charts 
  fl_chart: ^0.66.2 
   
  # UI 
  cupertino_icons: ^1.0.6 
  google_fonts: ^8.1.0 
  cached_network_image: ^3.3.1 
  shimmer: ^3.0.0 
   
  # Storage 
  shared_preferences: ^2.2.2 
   
  # Utils 
  intl: ^0.19.0 
  uuid: ^4.3.3 
  google_sign_in: ^7.2.0
  intl_phone_number_input: ^0.7.5
  loading_animation_widget: ^1.3.0
  flutter_markdown: ^0.7.7+1
 
dev_dependencies: 
  flutter_test: 
    sdk: flutter 
  flutter_lints: ^3.0.0 
  flutter_native_splash: ^2.4.7 # Make sure to check for the latest stable version
  flutter_launcher_icons: ^0.13.1

# ── LAUNCHER ICONS CONFIGURATION ──────────────────────────────────────────────
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
 
flutter: 
  uses-material-design: true 
  assets: 
    - assets/images/browse_bg.jpg
    - assets/images/compare_bg.jpg
    - assets/images/favorites_bg.jpg
    - assets/images/research_bg.jpg
    - assets/images/avatars/
    - assets/images/Logo/
    - assets/images/OnBoarding.jpg

fonts:
    - family: Aristotelica Pro Display Bold
      fonts:
        - asset: assets/fonts/Aristotelica-Pro-Display-Bold.ttf # Confirm exact path to your font file